/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sujay' at '4/28/19 5:35 PM' with Gradle 2.14.1
 *
 * @author Sujay, @date 4/28/19 5:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
